<?php
    include("conn.php");
    $pdo = getPDO();
    // 取得PRODUCT的TABLE內容
    // $statement = $pdo->prepare("SELECT PRODUCTS.ID, PRODUCTS.NAME, PRODUCTS.TAG 
    // ,PRODUCT_CATEGORY.NAME AS CATEGORY_NAME 
    // FROM PRODUCTS 
    // JOIN PRODUCT_CATEGORY ON PRODUCTS.CATEGORY_ID = PRODUCT_CATEGORY.ID");

    $statement = $pdo->prepare("SELECT 
        PRODUCTS.ID, 
        PRODUCT_CATEGORY.NAME AS CATEGORY_NAME, 
        PRODUCTS.NAME, 
        PRODUCTS.TAG, 
        MAX(CASE WHEN PRODUCTS_PRICE.SIZE = 'M' THEN PRODUCTS_PRICE.PRICE END) AS PRICE_M,
        MAX(CASE WHEN PRODUCTS_PRICE.SIZE = 'L' THEN PRODUCTS_PRICE.PRICE END) AS PRICE_L
    FROM PRODUCTS
    JOIN PRODUCT_CATEGORY ON PRODUCTS.CATEGORY_ID = PRODUCT_CATEGORY.ID
    JOIN PRODUCTS_PRICE ON PRODUCTS.ID = PRODUCTS_PRICE.PRODUCTS_ID
    GROUP BY PRODUCTS.ID");
    $statement->execute();
    $result = $statement->fetchAll(PDO::FETCH_ASSOC);

    echo json_encode($result);
?>